---
stages:
  data_ingestion:
    cmd: python src/churn/pipelines/pip_01_data_ingestion.py
    deps:
      - src/churn/pipelines/pip_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/web_churn.csv
      - artifacts/data_ingestion/metadata.json
