---
stages:
  data_ingestion:
    cmd: python src/churn/pipelines/pip_01_data_ingestion.py
    deps:
      - src/churn/pipelines/pip_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/web_churn.csv
      - artifacts/data_ingestion/metadata.json

  data_validation:
    cmd: python src/churn/pipelines/pip_02_data_validation.py
    deps:
      - src/churn/pipelines/pip_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/web_churn.csv
    outs:
      - artifacts/data_validation/status.json


  data_transformation:
    cmd: python src/churn/pipelines/pip_03_data_transformation.py
    deps: 
      - src/churn/pipelines/pip_03_data_transformation.py
      - config/config.yaml

    outs:
      - artifacts/data_transformation/X_test_transformed.joblib
      - artifacts/data_transformation/y_test.csv
      - artifacts/data_transformation/X_train_transformed.joblib
      - artifacts/data_transformation/y_train.csv
      - artifacts/data_transformation/X_val_transformed.joblib
      - artifacts/data_transformation/y_val.csv

  model_training:
    cmd: python src/churn/pipelines/pip_04_model_trainer.py
    deps:
      - src/churn/pipelines/pip_04_model_trainer.py
      - config/config.yaml

    outs:
      - artifacts/model_trainer/model.joblib

  model_evaluation:
    cmd: python src/churn/pipelines/pip_05_model_evaluation.py
    deps:
      - src/churn/pipelines/pip_05_model_evaluation.py
      - config/config.yaml

    outs:
      - artifacts/model_evaluation/pr_curve.png
      - artifacts/model_evaluation/roc_curve.png
      - artifacts/model_evaluation/evaluation_metrics.json
