---
stages:
  data_ingestion:
    cmd: python src/churn/pipelines/pip_01_data_ingestion.py
    deps:
      - src/churn/pipelines/pip_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/web_churn.csv
      - artifacts/data_ingestion/metadata.json

  data_validation:
    cmd: python src/churn/pipelines/pip_02_data_validation.py
    deps:
      - src/churn/pipelines/pip_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/web_churn.csv
    outs:
      - artifacts/data_validation/status.json

  model_training:
    cmd: python src/churn/pipelines/pip_04_model_trainer.py
    deps:
      - src/churn/pipelines/pip_04_model_trainer.py
      - config/config.yaml

    outs:
      - artifacts/model_trainer/model.joblib
