artifacts_root: artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion
  mongo_uri: mongodb+srv://Minich:Mydatabase.456@minich-data-repository.gzlkk1s.mongodb.net/
  database_name: churn
  collection_name: transformed_web_churn


data_validation:
  root_dir: artifacts/data_validation
  data_source: artifacts/data_ingestion/web_churn.csv
  status_file: artifacts/data_validation/status.json
  critical_columns: 
    - 'age'
    - 'gender'
    - 'region_category'
    - 'membership_category'
    - 'joined_through_referral'
    - 'preferred_offer_types'
    - 'internet_option'
    - 'recency'
    - 'avg_time_spent'
    - 'monetary'
    - 'frequency'
    - 'points_in_wallet' 
    - 'used_special_discount'
    - 'offer_application_preference'
    - 'past_complaint'
    - 'complaint_status'
    - 'feedback'
    - 'churn_risk_score'
    - 'medium_of_operation'
    - 'tenure_months'
    - 'visit_hour' 
    - 'login_spend_ratio'
    - 'login_transaction_ratio'

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/web_churn.csv
  numerical_cols:
    - 'age'
    - 'recency'
    - 'avg_time_spent'
    - 'monetary'
    - 'frequency'
    - 'points_in_wallet' 
    - 'tenure_months'
    - 'visit_hour' 
    - 'login_spend_ratio'
    - 'login_transaction_ratio'
                  
  categorical_cols:
    - 'gender'
    - 'region_category'
    - 'membership_category'
    - 'joined_through_referral'
    - 'preferred_offer_types'
    - 'internet_option'
    - 'used_special_discount'
    - 'offer_application_preference'
    - 'past_complaint'
    - 'complaint_status'
    - 'feedback'
    - 'medium_of_operation'

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/X_train_transformed.joblib
  val_data_path: artifacts/data_transformation/X_val_transformed.joblib
  model_name: model.joblib
  mlflow_uri: https://dagshub.com/minich-code/churnpred.mlflow

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/X_val_transformed.joblib
  test_target_variable: artifacts/data_transformation/y_val.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/evaluation_metrics.json
  mlflow_uri: https://dagshub.com/minich-code/churnpred.mlflow

model_validation:
  root_dir: artifacts/model_validation
  model_path: artifacts/model_trainer/model.joblib
  test_data_path: artifacts/data_transformation/X_test_transformed.joblib
  test_target_variable: artifacts/data_transformation/y_test.csv
  metric_file_name: artifacts/model_validation/validation_metrics.json
  mlflow_uri: https://dagshub.com/minich-code/churnpred.mlflow

